name: CI Workflow

on:
  push:

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

  build-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies and build backend
        working-directory: ./backend
        run: |
          go mod download
          go build ./...

      - name: Run backend tests
        working-directory: ./backend
        run: go test ./...
